version: '2.0'
services:
  predict:
    build: ./src/
    volumes:
      - ./src/:/app
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - INPUT_JSON=./input/list_to_predict.json
      - OUTPUT_DIR=./output/predict/
      - MODEL_DIR=./output/model/
      - IIIF_API_ROOT
      - IIIF_CACHE_DIR
      - TMP_DIR
      - BOUWDOSSIERS_OBJECTSTORE_PASSWORD
    command: "python /app/run_prediction.py"
