version: '2.0'
services:
  predict:
    build: .
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - OUTPUT_DIR=./output/predict/
      - MODEL_DIR=./output/model/
      - IIIF_API_ROOT
      - IIIF_CACHE_DIR
      - BOUWDOSSIERS_OBJECTSTORE_PASSWORD
    command: "/app/run_tests.sh && /app/run_linting.sh"
